### ISSUE TITLE
What is the __URLS textfile for?

### ISSUE THREAD

**Issue by rick9791** [Manic0892/rud#6]
All it displays is just a timestamp? Is that it?

**Comment by Manic0892** [comment]
Any URLs that were not able to be downloaded by one of the modules get logged into __URLs text file.  This is to allow users to manually download any files that the tool wasn't able to download, in addition to debugging.  The timestamp is placed to allow the log to grow over time--deleting the file will have no adverse effect.

If all you're seeing is the timestamp, then all URLs were able to be downloaded.
